services:
  - type: web
    name: cinemax-api
    runtime: docker
    dockerfilePath: ./MovieManagement.API/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
